SELECT COUNT(*) AS COUNT, GENERATION 
FROM (
    SELECT e.ID,
    CASE 
        WHEN e.PARENT_ID IS NULL THEN 1
        WHEN p1.PARENT_ID IS NULL THEN 2
        WHEN p2.PARENT_ID IS NULL THEN 3
        WHEN p3.PARENT_ID IS NULL THEN 4
        WHEN p4.PARENT_ID IS NULL THEN 5
        WHEN p5.PARENT_ID IS NULL THEN 6
        WHEN p6.PARENT_ID IS NULL THEN 7
        WHEN p7.PARENT_ID IS NULL THEN 8
        WHEN p8.PARENT_ID IS NULL THEN 9
        ELSE 10
    END AS GENERATION
    FROM ECOLI_DATA e
    LEFT JOIN ECOLI_DATA p1 ON e.PARENT_ID = p1.ID
    LEFT JOIN ECOLI_DATA p2 ON p1.PARENT_ID = p2.ID
    LEFT JOIN ECOLI_DATA p3 ON p2.PARENT_ID = p3.ID
    LEFT JOIN ECOLI_DATA p4 ON p3.PARENT_ID = p4.ID
    LEFT JOIN ECOLI_DATA p5 ON p4.PARENT_ID = p5.ID
    LEFT JOIN ECOLI_DATA p6 ON p5.PARENT_ID = p6.ID
    LEFT JOIN ECOLI_DATA p7 ON p6.PARENT_ID = p7.ID
    LEFT JOIN ECOLI_DATA p8 ON p7.PARENT_ID = p8.ID
    LEFT JOIN ECOLI_DATA child ON e.ID = child.PARENT_ID
    WHERE child.ID IS NULL
) result
GROUP BY GENERATION
ORDER BY GENERATION;